### ISSUE TITLE
Is it possitble to Install extensions inside the container

### ISSUE THREAD

**Issue by davestroker** [sweisgerber/docker-mopidy#3]
I just installed yout mopidy and snapcast images and love it.
However, I'm a newbie in using docker containers and was wandering if it is possible to install mopidy extensions like Mopidy-Party in the running mopidy container.

Thanks a lot!

**Comment by sweisgerber** [comment]
Yes it is, you can select them with the environment flag.

See the example here: https://github.com/sweisgerber/docker-mopidy/blob/a041909c2f0068122893baedc03fe7b6bd0c79b4/docker-compose.example.yml#L16

It is based on the linuxserver.io images, so this docu applies there as well: https://github.com/linuxserver/docker-mods/tree/universal-package-install?tab=readme-ov-file#package-install---universal-docker-mod.
